### ISSUE TITLE
Merging the 'blog' and 'posts' applications

### ISSUE THREAD

**Issue by choucavalier** [Dubrzr/golb#2]
It's probably because I'm a maniac or because I have obsessive compulsive disorder but the fact that those two apps exist separately troubles me a lot. If you don't mind, I'll merge them

**Comment by Dubrzr** [comment]
You are right! I'm working on reorganizing this :)

**Comment by Dubrzr** [comment]
Done, what do you think of those changes?

**Comment by choucavalier** [comment]
I still don't get why there should be 2 different modules 'blog' and 'articles'. For me an Article is a model in the 'blog' application.

**Comment by Dubrzr** [comment]
Then let's also put users module in blog module? blog is meant to be the main django module for this project, I can rename it to be more global like "site", but why not blog?
I also find it cleaner to have all article related models, template, views & urls in a single module. It also gives more readability, for example I just have to add url(r'article/', include(articles_urlpatterns)) in the urlpatterns variable of blog.urls.py file, consequently I don't have to add the "article/" prefix to every url that need it :) It's exactly the same for the users module. And for example, there is a single template folder for each application, I find it more readable and easy to maintain compared to a large folder containing all template files.
